######################################################################
# Automatically generated by qmake (3.0) Wed Dec 23 20:00:00 2015
######################################################################

TEMPLATE = app
QT += gui widgets
INCLUDEPATH += .

# Input
SOURCES += main.cpp
